config/routes.rb
Rails.application.routes.draw do



  root 'sessions#login'
  get '/login', to: "sessions#login", as: 'login'
  post '/login', to: "sessions#attempt_login"
  delete '/logout', to: "sessions#logout", as: "logout"

  # password reset routes
  resources :resets, only: [:new, :edit, :create, :update]

	# root 'users#index'

  resources :users
  resources :places

  get '/search', to: 'places#search'
  # the AJAX get request from the user.js file is looking for
  # the results action here
  get '/results', to: 'places#results'
  get '/friends', to: 'users#friends'
end

# Prefix Verb   URI Pattern                Controller#Action
#       root GET    /                          sessions#login
#      login GET    /login(.:format)           sessions#login
#            POST   /login(.:format)           sessions#attempt_login
#     logout DELETE /logout(.:format)          sessions#logout
#     resets POST   /resets(.:format)          resets#create
#  new_reset GET    /resets/new(.:format)      resets#new
# edit_reset GET    /resets/:id/edit(.:format) resets#edit
#      reset PATCH  /resets/:id(.:format)      resets#update
#            PUT    /resets/:id(.:format)      resets#update
#      users GET    /users(.:format)           users#index
#            POST   /users(.:format)           users#create
#   new_user GET    /users/new(.:format)       users#new
#  edit_user GET    /users/:id/edit(.:format)  users#edit
#       user GET    /users/:id(.:format)       users#show
#            PATCH  /users/:id(.:format)       users#update
#            PUT    /users/:id(.:format)       users#update
#            DELETE /users/:id(.:format)       users#destroy
#     places GET    /places(.:format)          places#index
#            POST   /places(.:format)          places#create
#  new_place GET    /places/new(.:format)      places#new
# edit_place GET    /places/:id/edit(.:format) places#edit
#      place GET    /places/:id(.:format)      places#show
#            PATCH  /places/:id(.:format)      places#update
#            PUT    /places/:id(.:format)      places#update
#            DELETE /places/:id(.:format)      places#destroy
#     search GET    /search(.:format)          places#search
#    results GET    /results(.:format)         places#results
#    friends GET    /friends(.:format)         users#friends

app/models/user.rb
class User < ActiveRecord::Base

	# removed validates password because has_secure_password does this for you
	validates :email, presence: true
	
	# we will add in additional validations later on
	
	# added avatar information 
	has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>"}, :default_url => "/images/:style/missing.png" 
	# validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*Z/
	validates_attachment :avatar, :content_type => { :content_type => ["image/jpeg", "image/gif", "image/png"] }

	has_many :favorites, dependent: :destroy
	has_many :places, through: :favorites

	has_many :comments, dependent: :destroy
	has_many :places, through: :comments

	has_secure_password

	def generate_password_reset_token!
	   update(password_reset_token: SecureRandom.urlsafe_base64(48))
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :current_user, except: [:new, :create]

  def index
  	@users = User.all
  end

  def friends
    @friends = User.where("lat IS NOT NULL")
    render json: @friends
  end

  def new
  	@user = User.new
  end

  def create
  	@user = User.create(user_params)
    puts params
  		if @user.save
        session[:user_id] = @user.id
  			redirect_to users_path, flash: {success: "#{@user.first_name} created"}
  		else
  			render :new
  		end
  end

  def show
  end

  def edit
  end	

  def update
    @current_user.update user_params
    if @current_user.save
      redirect_to users_path, flash: {success: "#{@current_user.first_name} updated"}
    else
      render :edit
    end
  end

  def destroy
    @current_user.destroy
    session[:user_id] = nil
    flash[:notice] = "#{@current_user.first_name} has been deleted!"
    redirect_to login_path
    

  end



# added avatar info into the def user_params
  private

  def user_params
  	params.require(:user).permit(
  		:first_name,
      :avatar,
  		:email,
  		:img_url,
  		:address,
  		:password,
      :password_reset_token,
      :lat,
      :lng
  		)
  end	
  # We don't want other users to edit another user's info or favorites. 
  # This method below will allow us to ensure that the correct user has access to edit his or her info. 
  def ensure_correct_user 
    # compare some params vs something in the session/current_user
    unless params[:id].to_i == session[:user_id]
      redirect_to all_teams_path, alert: "Not Authorized"
    end
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_errors.html.erb
<% if instance.errors.any? %>
	<ul>
		<% instance.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
		<% end %>
	</ul>
<% end %>

app/views/users/_form.html.erb
<%= form_for @user, :html => { :multipart => true }  do |f| %>
	<%= f.file_field :avatar %>

	<%= render partial: 'users/errors', locals:{instance:@user} %>
	<div class="form-group">
		<%= f.label :first_name %>
		<%= f.text_field :first_name %>
	</div>

	<div class="form-group">
		<%= f.label :email %>
		<%= f.text_field :email %>
	</div>

	<div class="form-group">
		<%= f.label :img_url %>
		<%= f.text_field :img_url %>
	</div>

	<div class="form-group">
		<%= f.label :address %>
		<%= f.text_field :address %>
	</div>

	<div class="form-group">
		<%= f.label :password %>
		<%= f.password_field :password %>
	</div>

	<div>
		<%= f.submit %>
	</div>

<% end %>

app/views/users/edit.html.erb
<div class="edit-picture-page">

<div class="ui inverted segment show">
    <div class="ui inverted secondary menu">
    <a class="active item">
			<%= image_tag("median-logo2.png") %>
		</a>
		
		<a class="active item image">
			<%= image_tag("median-icon2.png") %>
		</a>
		
		<a class="active item">
			Home
		</a>
		
		<a class="active item">
			Contact
		</a>
      <a class="active item">
        About
      </a>  
    </div>
  </div> 

<div class="edit-profile-form">
<h1 class="show-h1">Edit Your Profile</h1>

<%= form_for(@current_user) do |f| %>
	<%= render partial: 'users/errors', locals:{instance:@current_user} %>
	<div class="edit-form">
	<div class="form-group first-name">
		<%= f.label :first_name %><br>
		<%= f.text_field :first_name %>
	</div>

	<div class="form-group">
		<%= f.label :email %><br>
		<%= f.text_field :email %>
	</div>

	<div class="form-group">
		<%= f.label :img_url %><br>
		<%= f.text_field :img_url %>
	</div>

	<div class="form-group">
		<%= f.label :address %><br>
		<%= f.text_field :address %>
	</div>

	<div class="form-group">
		<%= f.label :password %><br>	
		<%= f.password_field :password %>
	</div>
<p></p>
	<div>
		<%= f.submit %>
	</div>
</div>	

<% end %>	
</div>
</div>

app/views/users/index.html.erb
<div id="map-index">
	<div class="ui inverted segment">
		
		<a class="active item">
			<%= image_tag("median-logo3.png") %>
		</a>
		<a class="active item image">
			<%= image_tag("median-icon2.png") %>
		</a>
		<a class="active item">
			Home
		</a>
		<a class="active item">
			Contact
		</a>
		<a class="active item">
			About
		</a>
		<a class="active item">
			<!-- The class="index" in the h1 tag below is needed (the users.js file is looking for it); please don't remove it -->
			<h1 class="index">Welcome To Median, <%= @current_user.first_name %>!</h1>
		</a>
	</div>

<!-- testing logged in users -->
<button id="friends">See Who's Logged In!</button>

<%= form_tag("/search", method: "get") do %>
  <%= label_tag(:q, "Search for a category:", ) %>
  <%= text_field_tag(:q, nil, class:"user_term", autofocus: true) %>
  <%= submit_tag("Search") %>
<% end %>

	<div class="ui two column centered grid">
		<div class="column first">
	
	<div class ="search-container">
		
<!-- 		<form class="ui form"> -->
		</div>
		<!-- </form>	 -->

	</div>		

		</div>

		<div class="ui grid">
			<div class="three column row">
				<div class="two wide column"></div>
				<div class="twelve wide column"><div id='map'></div></div>
				<div class="two wide column"></div>
			</div>
		</div>


			<div class="column first">
				<div id='map'></div>
			</div>	
</div>		

<!-- <div class="ui grid">
	<div id='map' class="eight column row"></div>
</div> -->

app/views/users/new.html.erb
<div id="signup-larger" class="get-location">
	<div class="signup-background-color">
		<h1>
			<div class="median-logo">
				<%= image_tag("median-logo1.png") %>
			</div>
		</h1>

		<h3>Signup</h3>

		<%= form_for @user, :html => { :multipart => true }  do |f| %>
		<%= render partial: 'users/errors', locals:{instance:@user} %>
	
			<div class="form-group">
				<div class="label">
					<div class="form-font">
						<%= f.label :first_name %><br>
					</div>
				</div>
					<%= f.text_field :first_name %>
			</div>

			<div class="form-group">
				<div class="label"></div>	
					<%= f.label :email %><br>
					<%= f.text_field :email %>
			</div>

			<div class="form-group">
				<%= f.label :img_url %><br>
				<%= f.text_field :img_url %>
			</div>

			<div class="form-group">
				<%= f.label :address %><br>
				<%= f.text_field :address %>
			</div>

			<div class="form-group">
				<%= f.label :password %><br>
				<%= f.password_field :password %>
			</div>

			<div class="avatar-label">
				<%= f.file_field :avatar %>
			</div>
			<%= f.hidden_field :lat %>
			<%= f.hidden_field :lng %>
			<div class="submit-button">
				<%= f.submit%>
			</div>
			
			<div class="signup-link">
          <%= link_to "Have an existing account? Login here", login_path %>
      </div>

	</div>

	<div class="ui inverted segment footer">
      <div class="ui inverted secondary menu">
      	 <a class="active item">
           Home
         </a>
         <a class="active item">
           About
         </a> 
         <a class="active item">
           Contact
         </a>  
       </div>
     </div> 


</div>	
	<% end %>

app/views/users/show.html.erb
<body class="show-body">

	<div class="ui inverted segment show">
    <div class="ui inverted secondary menu">
      <a class="active item">
        About
      </a>  
    </div>
  </div> 
	
	<div class="show-profile-info">
		<h1 class="show-h1">Hello, <%= @current_user.first_name %>!</h1>

		<%= image_tag @current_user.avatar.url %>
		<%= image_url @current_user.avatar.url(:medium) %>
		<%= image_url @current_user.avatar.url(:thumb) %>

		<ul>
			<li>
				<img src="<%= @current_user.img_url %>">
			</li>
			<li>
				<%= @current_user.first_name %></li>
			<li>
				<%= @current_user.email %></li>
			<li>
				<%= @current_user.address%>
			</li>

			<li>
				<%= link_to "Edit #{@current_user.first_name}'s Info",edit_user_path(@current_user)%><br>
			</li>
			<li>	
				<%= link_to "Delete #{@current_user.first_name}"'s account', user_path(@current_user), method: :delete %><br>
			</li>
		</ul>
	</div>	
</body>	