config/routes.rb
Rails.application.routes.draw do



  root 'sessions#login'
  get '/login', to: "sessions#login", as: 'login'
  post '/login', to: "sessions#attempt_login"
  delete '/logout', to: "sessions#logout", as: "logout"

  # password reset routes
  resources :resets, only: [:new, :edit, :create, :update]

	# root 'users#index'

  resources :users
  resources :places

  get '/search', to: 'places#search'
  # the AJAX get request from the user.js file is looking for
  # the results action here
  get '/results', to: 'places#results'
  get '/friends', to: 'users#friends'
end

# Prefix Verb   URI Pattern                Controller#Action
#       root GET    /                          sessions#login
#      login GET    /login(.:format)           sessions#login
#            POST   /login(.:format)           sessions#attempt_login
#     logout DELETE /logout(.:format)          sessions#logout
#     resets POST   /resets(.:format)          resets#create
#  new_reset GET    /resets/new(.:format)      resets#new
# edit_reset GET    /resets/:id/edit(.:format) resets#edit
#      reset PATCH  /resets/:id(.:format)      resets#update
#            PUT    /resets/:id(.:format)      resets#update
#      users GET    /users(.:format)           users#index
#            POST   /users(.:format)           users#create
#   new_user GET    /users/new(.:format)       users#new
#  edit_user GET    /users/:id/edit(.:format)  users#edit
#       user GET    /users/:id(.:format)       users#show
#            PATCH  /users/:id(.:format)       users#update
#            PUT    /users/:id(.:format)       users#update
#            DELETE /users/:id(.:format)       users#destroy
#     places GET    /places(.:format)          places#index
#            POST   /places(.:format)          places#create
#  new_place GET    /places/new(.:format)      places#new
# edit_place GET    /places/:id/edit(.:format) places#edit
#      place GET    /places/:id(.:format)      places#show
#            PATCH  /places/:id(.:format)      places#update
#            PUT    /places/:id(.:format)      places#update
#            DELETE /places/:id(.:format)      places#destroy
#     search GET    /search(.:format)          places#search
#    results GET    /results(.:format)         places#results
#    friends GET    /friends(.:format)         users#friends

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hangout</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => false %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => false %>
  <script src="https://maps.googleapis.com/maps/api/js?v=3.20&signed_in=true&libraries=geometry"></script>
  <%= csrf_meta_tags %>
</head>
<body class="<%= controller_name %> <%= action_name %>">
<% if logged_in? %>
<%= link_to "usersIndex", users_path() %>
<%= link_to "User Show Page", user_path(session[:user_id])%>
<%= link_to "Sign Out", logout_path, method: :delete %>
<% end  %>
  <div class="main container">
    <% flash.each do |key, value| %>
      <% if key == "notice" %>
        <%= content_tag :div, value, class: "text-center alert alert-warning" %>
      <% elsif key == "alert" %>
        <%= content_tag :div, value, class: "text-center alert alert-danger" %>
      <% else %>
        <%= content_tag :div, value, class: "text-center alert alert-success" %>
      <% end %>
    <% end %>
    <%= yield %>

  </div>

</body>
</html>